### ISSUE TITLE
Typo in findsecrets ignore comment

### ISSUE THREAD

**Issue by maksymilian-majer** [clevertech/findsecrets#1]
The value is `finsecrets-ignore-file` and it's supposed to be `findsecrets-ignore-file`:

https://github.com/clevertech/findsecrets/blob/40a918bbbdd4a1098ce22407a0dde940b1e988c1/index.js#L32

**Comment by gimenete** [comment]
whoops, thanks. I'll fix it

**Comment by gimenete** [comment]
Fixed.
